//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TargetRecognition.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TARGETRECOGNITION_DIALOG      102
#define IDR_MAINFRAME                   128
#define IDD_FACEDB_DIALOG               129
#define IDD_ADDGROUP_DIALOG             130
#define IDD_EDIT_GROUP_DIALOG           131
#define IDD_PERSON_OPREATE_DIALOG       132
#define IDD_ADD_PERSON_DIALOG           133
#define IDD_SEARCH_BY_PIC_DIALOG        134
#define IDD_DISPATCH_DIALOG             136
#define IDD_DOWNLOAD_RECOGNITION_DIALOG 137
#define IDD_DIALOG_DISPATCH_CHANNEL     138
#define IDC_IPADDRESS                   1000
#define IDC_EDIT_PORT                   1001
#define IDC_EDIT_USER                   1002
#define IDC_EDIT_PASS                   1003
#define IDC_BUTTON_LOGIN                1004
#define IDC_COMBO_CHANNEL               1010
#define IDC_BUTTON_ATTACH               1011
#define IDC_COMBO_FILE_TYPE             1011
#define IDC_BUTTON_DETEACH              1012
#define IDC_BUTTON_REALPLAY             1013
#define IDC_STATIC_BIG_PIC              1014
#define IDC_STATIC_PERSON1              1015
#define IDC_STATIC_CANDI1               1018
#define IDC_BUTTON_FACE_DB              1021
#define IDC_STATIC_VIDEO                1022
#define IDC_DATE_EVENT_TIME             1025
#define IDC_EDIT_SEX                    1026
#define IDC_EDIT_AGE                    1027
#define IDC_EDIT_EVENT_TIME             1028
#define IDC_EDIT_SKINCOLOR              1029
#define IDC_EDIT_EYE                    1030
#define IDC_EDIT_MOUTH                  1031
#define IDC_EDIT_MASK                   1032
#define IDC_EDIT_BEARD                  1033
#define IDC_EDIT_SIMILARITY             1035
#define IDC_EDIT_GROUP_ID               1036
#define IDC_EDIT_GROUP_NAME             1037
#define IDC_EDIT_PERSON_NAME            1038
#define IDC_CHECK_ALL                   1040
#define IDC_RADIO_group1                1041
#define IDC_RADIO_group2                1042
#define IDC_RADIO_group3                1043
#define IDC_RADIO_group4                1044
#define IDC_RADIO_group5                1045
#define IDC_RADIO_group6                1046
#define IDC_RADIO_group7                1047
#define IDC_RADIO_group8                1048
#define IDC_RADIO_group9                1049
#define IDC_RADIO_group10               1050
#define IDC_DB_NAME1                    1051
#define IDC_DB_NAME2                    1052
#define IDC_DB_NAME3                    1053
#define IDC_DB_NAME4                    1054
#define IDC_DB_NAME5                    1055
#define IDC_DB_NAME6                    1056
#define IDC_DB_NAME7                    1057
#define IDC_DB_NAME8                    1058
#define IDC_DB_NAME9                    1059
#define IDC_DB_NAME10                   1060
#define IDC_PERSON_NUM1                 1062
#define IDC_PERSON_NUM2                 1063
#define IDC_PERSON_NUM3                 1064
#define IDC_PERSON_NUM4                 1065
#define IDC_PERSON_NUM5                 1066
#define IDC_PERSON_NUM6                 1067
#define IDC_PERSON_NUM7                 1068
#define IDC_PERSON_NUM8                 1069
#define IDC_PERSON_NUM9                 1070
#define IDC_PERSON_NUM10                1071
#define IDC_CHECK1                      1072
#define IDC_CHECK_ATTRIBUTE_ENABLE      1072
#define IDC_CHECK2                      1073
#define IDC_CHECK3                      1074
#define IDC_CHECK4                      1075
#define IDC_CHECK5                      1076
#define IDC_CHECK6                      1077
#define IDC_CHECK7                      1078
#define IDC_CHECK8                      1079
#define IDC_CHECK9                      1080
#define IDC_CHECK10                     1081
#define IDC_EDIT_ADD_GROUP_NAME         1094
#define IDC_EDIT_ADD_GROUP_Similarity   1095
#define IDC_EDIT_NAME                   1096
#define IDC_COMBO_SEX                   1097
#define IDC_COMBO_CARDTYPE              1098
#define IDC_EDIT_CARD_NUM               1099
#define IDC_EDIT_PROVINCE               1100
#define IDC_EDIT_CITY                   1101
#define IDC_BUTTON_Edit                 1103
#define IDC_BUTTON_REFRESH              1104
#define IDC_BUTTON_DELETE               1105
#define IDC_BUTTON_ADD                  1106
#define IDC_BUTTON_SEARCH               1107
#define IDC_BUTTON_SearchByPic          1108
//#define IDC_BUTTON_SEARCHBUPIC          1108
#define IDC_group_PerPage               1111
#define IDC_group_NextPage              1112
#define IDC_EDIT_NAME1                  1114
#define IDC_EDIT_NAME2                  1115
#define IDC_EDIT_NAME3                  1116
#define IDC_EDIT_NAME4                  1117
#define IDC_EDIT_NAME5                  1118
#define IDC_EDIT_NAME6                  1119
#define IDC_EDIT_NAME7                  1120
#define IDC_EDIT_NAME8                  1121
#define IDC_EDIT_NAME9                  1122
#define IDC_EDIT_NAME10                 1123
#define IDC_EDIT_SEX1                   1124
#define IDC_EDIT_SEX2                   1125
#define IDC_EDIT_SEX3                   1126
#define IDC_EDIT_SEX4                   1127
#define IDC_EDIT_SEX5                   1128
#define IDC_EDIT_SEX6                   1129
#define IDC_EDIT_SEX7                   1130
#define IDC_EDIT_SEX8                   1131
#define IDC_EDIT_SEX9                   1132
#define IDC_EDIT_SEX10                  1133
#define IDC_EDIT_CITY1                  1144
#define IDC_EDIT_CITY2                  1145
#define IDC_EDIT_CITY3                  1146
#define IDC_EDIT_CITY4                  1147
#define IDC_EDIT_CITY5                  1148
#define IDC_EDIT_CITY6                  1149
#define IDC_EDIT_CITY7                  1150
#define IDC_EDIT_CITY8                  1151
#define IDC_EDIT_CITY9                  1152
#define IDC_EDIT_CITY10                 1153
#define IDC_EDIT_CARDTYPE1              1154
#define IDC_EDIT_CARDTYPE2              1155
#define IDC_EDIT_CARDTYPE3              1156
#define IDC_EDIT_CARDTYPE4              1157
#define IDC_EDIT_CARDTYPE5              1158
#define IDC_EDIT_CARDTYPE6              1159
#define IDC_EDIT_CARDTYPE7              1160
#define IDC_EDIT_CARDTYPE8              1161
#define IDC_EDIT_CARDTYPE9              1162
#define IDC_EDIT_CARDTYPE10             1163
#define IDC_EDIT_CARDNUMBER1            1164
#define IDC_EDIT_CARDNUMBER2            1165
#define IDC_EDIT_CARDNUMBER3            1166
#define IDC_EDIT_CARDNUMBER4            1167
#define IDC_EDIT_CARDNUMBER5            1168
#define IDC_EDIT_CARDNUMBER6            1169
#define IDC_EDIT_CARDNUMBER7            1170
#define IDC_EDIT_CARDNUMBER8            1171
#define IDC_EDIT_CARDNUMBER9            1172
#define IDC_EDIT_CARDNUMBER10           1173
#define IDC_PersonGroupID               1174
#define IDC_BUTTON_PER                  1175
#define IDC_BUTTON_NEXT                 1176
#define IDC_RADIO_PERSON1               1177
#define IDC_RADIO_PERSON2               1178
#define IDC_RADIO_PERSON3               1179
#define IDC_RADIO_PERSON4               1180
#define IDC_RADIO_PERSON5               1181
#define IDC_RADIO_PERSON6               1182
#define IDC_RADIO_PERSON7               1183
#define IDC_RADIO_PERSON8               1184
#define IDC_RADIO_PERSON9               1185
#define IDC_RADIO_PERSON10              1186
#define IDC_EDIT_ADD_NAME               1186
#define IDC_BUTTON_PERSON_ADD           1187
#define IDC_COMBO_ADD_SEX               1187
#define IDC_BUTTON_PERSON_EDIT          1188
#define IDC_BUTTON_PERSON_DEL           1189
#define IDC_COMBO_ADD_ACRDTYPE          1189
#define IDC_EDIT_ADD_CARDID             1190
#define IDC_PersonGroupName             1190
#define IDC_PersonBirthDayStartex       1190
#define IDC_STATIC_PERSON_PIC           1192
#define IDC_OPEN_PIC                    1193
#define IDC_SEARCH_PIC                  1194
#define IDC_OPEN_SEARCH_PIC             1195
#define IDC_BUTTON_DISPATCH             1197
#define IDC_DB_NAME                     1200
#define IDC_COMBO_DBTYPE                1201
#define IDC_ADD_YEAR                    1202
#define IDC_ADD_MONTH                   1203
#define IDC_DATE_START                  1203
#define IDC_ADD_DAY                     1204
#define IDC_DATE_END                    1204
#define IDC_TIME_START                  1205
#define IDC_TIME_END                    1206
#define IDC_SEARCH_DBTYPE               1208
#define IDC_COMBO_ALARM_TYPE            1208
#define IDC_SEARCH_SIMILARITY           1209
#define IDC_COMBO_QUERY_SEX             1209
#define IDC_SEARCH_CHANNEL              1210
#define IDC_SEARCH_StartYear            1211
#define IDC_COMBO_QUERY_GLASSES         1211
#define IDC_SEARCH_StartMonth           1212
#define IDC_COMBO_QUERY_MASK            1212
#define IDC_SEARCH_StartDay             1213
#define IDC_COMBO_QUERY_BREAD           1213
#define IDC_SEARCH_EndYear              1214
#define IDC_COMBO_QUERY_EMOTION         1214
#define IDC_SEARCH_EndMonth             1215
#define IDC_SEARCH_EndDay               1216
#define IDC_SEARCH_SIMILARITY_COMBOX    1217
#define IDC_BIRTHDAY_start_year         1221
#define IDC_BIRTHDAY_start_month        1222
#define IDC_BIRTHDAY_start_day          1223
#define IDC_BIRTHDAY_end_year           1224
#define IDC_SEARCH_PROGRESS             1224
#define IDC_BIRTHDAY_end_month          1225
#define IDC_RESULT_CARDTYPE3            1225
#define IDC_BIRTHDAY_end_day            1226
#define IDC_RESULT_CARDTYPE4            1226
#define IDC_LIST_QUERY_RESULT           1240
#define IDC_STATIC_SEARCH_INFO          1240
#define IDC_SELECT_PersonPicture        1241
#define IDC_BUTTON_QUERY_START          1247
#define IDC_BUTTON_QUERY_STOP           1248
#define IDC_BUTTON_QUERY_DOWNLOAD       1249
#define IDC_COMBO_CHANNEL_QUERY         1250
#define IDC_EDIT_QUERY_COUNT            1251
#define IDC_BUTTON_QUERY_PREPAGE        1252
#define IDC_BUTTON_QUERY_NEXTPAGE       1253
#define IDC_STATIC_REALPLAY_PIC         1255
#define IDC_PROGRESS_QUERY              1256
#define IDC_PROGRESS_QUERY2             1257
#define IDC_BUTTON_STOPPLAYBACK         1258
#define IDC_SEARCH_PERSON_INFO          1262
#define IDC_EDIT_BIRTHDAY               1264
#define IDC_dispatch_groupId            1267
#define IDC_dispatch_groupName          1268
#define IDC_dispatch_channel            1270
#define IDC_dispatch_similarity         1271
#define IDC_dispatch_channel2           1271
#define IDC_DISPATCH_SIMILARITY_COM     1271
#define IDC_LIST3                       1272
#define IDC_LIST_DISPATCH               1272
#define IDC_dispatch_add                1273
#define IDC_dispatch_delete             1274
#define IDC_dispatch_dispatch           1275
#define IDC_dispatch_refresh            1276
#define IDC_dispatch_addall             1277
#define IDC_dispatch_delete2            1278
#define IDC_PersonBirthDayStart         1285
#define IDC_PersonBirthDayStart2        1286
#define IDC_AddPersonBirthDay           1286
#define IDC_PersonBirthDayEnd           1286
#define IDC_AddPersonGroupID            1287
#define IDC_AddPersonGroupID2           1288
#define IDC_AddPersonGroupName          1288
#define IDC_EVENT_TYPE                  1289
#define IDC_BUTTON1                     1290
#define IDC_BUTTON_DISPATCH_CHANNEL     1290
#define IDC_BUTTON_SEARCHPIC_STOP       1290
#define IDC_DISPATCH_FORCHANNEL_REFRESH 1290
#define IDC_EDIT1                       1291
#define IDC_EDIT_SEARCHBUPIC_COUNT      1291
#define IDC_EDIT_AGE1                   1291
#define IDC_EDIT_SimilaryRange1         1292
#define IDC_EDIT3                       1293
#define IDC_COMBO_DISPATCH_GROUPID      1294
#define IDC_COMBO_DISPATCH_CHANNEL      1295
#define IDC_DISPATCHCHANNEL_CHANNEL     1295
#define IDC_DISPATCHCHANNEL_GROUPID     1296
#define IDC_DISPATCHCHANNEL_SIMILARITY  1297
#define IDC_STARTDATE_SEARCHPIC         1298
#define IDC_DISPATCHCHANNEL_SIMILARITY_COM 1298
#define IDC_ENDDATE_SEARCHPIC           1299
#define IDC_EDIT_AGE2                   1300
#define IDC_EDIT_AGE4                   1301
#define IDC_EDIT_SimilaryRange2         1301
#define IDC_BIRTHDAY1                   2000
#define IDC_BIRTHDAY2                   2001
#define IDC_BIRTHDAY3                   2002
#define IDC_BIRTHDAY4                   2003
#define IDC_BIRTHDAY5                   2004
#define IDC_BIRTHDAY6                   2005
#define IDC_BIRTHDAY7                   2006
#define IDC_BIRTHDAY8                   2007
#define IDC_BIRTHDAY9                   2008
#define IDC_BIRTHDAY10                  2009
#define IDC_BIRTHDAY_MONTH1             2010
#define IDC_BIRTHDAY_MONTH2             2011
#define IDC_BIRTHDAY_MONTH3             2012
#define IDC_BIRTHDAY_MONTH4             2013
#define IDC_BIRTHDAY_MONTH5             2014
#define IDC_BIRTHDAY_MONTH6             2015
#define IDC_BIRTHDAY_MONTH7             2016
#define IDC_BIRTHDAY_MONTH8             2017
#define IDC_BIRTHDAY_MONTH9             2018
#define IDC_BIRTHDAY_MONTH10            2019
#define IDC_BIRTHDAY_DAY1               2020
#define IDC_BIRTHDAY_DAY2               2021
#define IDC_BIRTHDAY_DAY3               2022
#define IDC_BIRTHDAY_DAY4               2023
#define IDC_BIRTHDAY_DAY5               2024
#define IDC_BIRTHDAY_DAY6               2025
#define IDC_BIRTHDAY_DAY7               2026
#define IDC_BIRTHDAY_DAY8               2027
#define IDC_BIRTHDAY_DAY9               2028
#define IDC_BIRTHDAY_DAY10              2029
#define IDC_EDIT_INDEX1                 2030
#define IDC_EDIT_INDEX2                 2031
#define IDC_EDIT_INDEX3                 2032
#define IDC_EDIT_INDEX4                 2033
#define IDC_EDIT_INDEX5                 2034
#define IDC_EDIT_INDEX6                 2035
#define IDC_EDIT_INDEX7                 2036
#define IDC_EDIT_INDEX8                 2037
#define IDC_EDIT_INDEX9                 2038
#define IDC_EDIT_INDEX10                2039
#define IDC_SIMILARITY_CHANNEL1         2040
#define IDC_SIMILARITY_CHANNEL2         2041
#define IDC_SIMILARITY_CHANNEL3         2042
#define IDC_SIMILARITY_CHANNEL4         2043
#define IDC_SIMILARITY_CHANNEL5         2044
#define IDC_SIMILARITY_CHANNEL6         2045
#define IDC_SIMILARITY_CHANNEL7         2046
#define IDC_SIMILARITY_CHANNEL8         2047
#define IDC_SIMILARITY_CHANNEL9         2048
#define IDC_SIMILARITY_CHANNEL10        2049
#define IDC_GROUP_ID1                   2060
#define IDC_GROUP_ID2                   2061
#define IDC_GROUP_ID3                   2062
#define IDC_GROUP_ID4                   2063
#define IDC_GROUP_ID5                   2064
#define IDC_GROUP_ID6                   2065
#define IDC_GROUP_ID7                   2066
#define IDC_GROUP_ID8                   2067
#define IDC_GROUP_ID9                   2068
#define IDC_GROUP_ID10                  2069
#define IDC_RESULT_NAME                 3500
#define IDC_RESULT_SEX                  3501
#define IDC_RESULT_YEAR                 3502
#define IDC_RESULT_MONTH                3503
#define IDC_RESULT_DAY                  3504
#define IDC_RESULT_AGE                  3505
#define IDC_RESULT_CARDTYPE             3506
#define IDC_RESULT_CARDID               3507
#define IDC_RESULT_GLASSES              3508
#define IDC_RESULT_EYE                  3510
#define IDC_RESULT_Mouth                3511
#define IDC_RESULT_Mask                 3512
#define IDC_RESULT_Beard                3513
#define IDC_RESULT_Attractive           3514
#define IDC_EDIT_PIC_SIMILARITY1        3515
#define IDC_RESULT_NAME2                3800
#define IDC_RESULT_SEX2                 3801
#define IDC_RESULT_YEAR2                3802
#define IDC_RESULT_MONTH2               3803
#define IDC_RESULT_DAY2                 3804
#define IDC_RESULT_AGE2                 3805
#define IDC_RESULT_CARDTYPE2            3806
#define IDC_RESULT_CARDID2              3807
#define IDC_RESULT_GLASSES2             3808
#define IDC_RESULT_EYE2                 3810
#define IDC_RESULT_Mouth2               3811
#define IDC_RESULT_Mask2                3812
#define IDC_RESULT_Beard2               3813
#define IDC_RESULT_Attractive2          3814
#define IDC_EDIT_PIC_SIMILARITY2        3815
#define IDC_RESULT_PIC                  4000
#define IDC_RESULT_PIC2                 4001
#define IDC_DISPATCH_FORCHANNEL_CLEAR   5001
#define IDC_DISPATCH_FORCHANNEL_DELETE  5002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1301
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
