//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EntranceAccessDevices.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_REALLOADPICTURE_DIALOG      102
#define IDD_ENTRANCEACCESSDEVICES_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_BW_LIST              132
#define IDR_MENU1                       136
#define IDD_DIALOG_PARKINGSPACELIGHTGROUP 137
#define IDD_DIALOG_PARKING              137
#define IDD_DIALOG_STROBESET            137
#define IDD_DIALOG_PARKINGSPACELIGHTSTATE 139
#define IDD_DIALOG_BLACKWHILTLIST       139
#define IDD_DIALOG_PARKINGSPACELIGHTPLAN 140
#define IDD_DIALOG_TALK                 140
#define IDD_DIALOG1                     141
#define IDD_DIALOG_LATTICESCREEN        141
#define IDD_DIALOG_LATTICESCREEN2       142
#define IDD_DIALOG_SCREENSHOW_DETAIL    143
#define IDC_IPADDRESS_IP                1001
#define IDC_EDIT_PORT                   1002
#define IDC_EDIT_USERNAME               1003
#define IDC_EDIT_PASSWORD               1004
#define IDC_BUTTON_LOGIN                1005
#define IDC_BUTTON_LOGOUT               1006
#define IDC_BUTTON_EVENT_RULE           1007
#define IDC_BUTTON_DATA_QUERY           1008
#define IDC_COMBO_PREVIEW_CHANNEL       1009
#define IDC_STATIC_PN                   1011
#define IDC_STATIC_PREVIEW              1012
#define IDC_STATIC_PIC                  1013
#define IDC_STATIC_PICTURE              1013
#define IDC_CHECK_REFRESH_PIC           1019
#define IDC_BUTTON_START                1020
#define IDC_CHECK_SHOW_FULL_PIC         1021
#define IDC_BUTTON_START2               1021
#define IDC_LIST_EVENT_CHANNEL          1022
#define IDC_BUTTON_START_PREVIEW        1024
#define IDC_LISTCTRL_REAL_EVENT         1026
#define IDC_LIST_RESULT                 1027
#define IDC_LISTCTRL_REAL_EVENT2        1027
#define IDC_LISTCTRL_EVENT              1027
#define IDC_STATIC_PL                   1028
#define IDC_COMBO_DISPLAY_FILTER        1039
#define IDC_BUTTON_MANUAL_SNAP          1043
#define IDC_BUTTON_STOP                 1044
#define IDC_BUTTON_CHN_ANTI_SEL         1045
#define IDC_BUTTON_STOP2                1045
#define IDC_BUTTON_STOP_PREVIEW         1046
#define IDC_BUTTON_TYPE_SEL_ALL         1047
#define IDC_LIST_EVENT_DISPLAY          1048
#define IDC_BUTTON_TYPE_ANTI_SEL        1048
#define IDC_EDIT_SPEED2                 1054
#define IDC_BUTTON_CLEAR                1055
#define IDC_STATIC_ALARM_COUNT          1056
#define IDC_BUTTON_CLEAR2               1057
#define IDC_BUTTON_CLEAR_DATA           1057
#define IDC_COMBO_STATE                 1064
#define IDC_BUTTON_UPDATE_STATE         1065
#define IDC_STATIC_ACCURACY             1067
#define IDC_STATIC_LP                   1067
#define IDC_STATIC_EVENT_LP_IMAGE       1068
#define IDC_CHECK_WITH_DATA             1074
#define IDC_COMBO_CANNALMS              1075
#define IDC_BUTTON_PAUSE                1087
#define IDC_BUTTON_OPEN_STROBE          1089
#define IDC_COMBO_CHANNEL               1090
#define IDC_BUTTON_BW_LIST              1091
#define IDC_BUTTON_TRAFFIC_FLOW         1092
#define IDC_BUTTON_TRAFFIC_QUERY        1093
#define IDC_COMBO_VEHICLECOLOR2         1097
#define IDC_CHECK1                      1103
#define IDC_CHECK_OPEN                  1103
#define IDC_CHECK_CALLEVENT             1103
#define IDC_CHECK_OPEN_TYPE1            1103
#define IDC_CHECK2                      1104
#define IDC_COMBO_CODETYPE              1104
#define IDC_CHECK_OPEN_TYPE2            1104
#define IDC_EDIT1                       1105
#define IDC_COMBO_TRANSMITTYPE          1105
#define IDC_EDIT_PLATENUMBER            1105
#define IDC_EDIT_SCREENSHOW_TEXT        1105
#define IDD_DIALOG_BROADCAST_DETAIL     1105
#define IDC_EDIT_BROADCAST_TEXT         1105
#define IDC_CHECK3                      1106
#define IDC_EDIT8                       1106
#define IDC_BUTTON_BROWSE               1106
#define IDC_COMBO_SPEAKERID             1106
#define IDC_CHECK_TIME                  1106
#define IDC_EDIT_PARKTIME               1106
#define IDC_EDIT9                       1107
#define IDC_BUTTON_BEGINTALK            1107
#define IDC_EDIT_OWNEROFCAR            	1107
#define IDC_EDIT10                      1108
#define IDC_BUTTON_STOPTALK             1108
#define IDC_EDIT_SUBUSERTYPE            1108
#define IDC_PROGRESS1                   1109
#define IDC_EDIT11                      1109
#define IDC_EDIT_REMAINDAY              1109
#define IDC_EDIT12                      1110
#define IDC_EDIT_hours                  1110
#define IDC_EDIT_PARKCHARGE             1110
#define IDC_EDIT13                      1111
#define IDC_EDIT_minutes                1111
#define IDC_EDIT_REMAINSPACE            1111
#define IDC_RADIO1                      1112
#define IDC_EDIT_seconds                1112
#define IDC_RADIO_NOPASS                1112
#define IDC_RADIO2                      1113
#define IDC_EDIT_houre                  1113
#define IDC_RADIO_PASS                  1113
#define IDC_EDIT6                       1114
#define IDC_EDIT7                       1115
#define IDC_EDIT_OUTTIME                1115
#define IDC_COMBO_STATUS                1116
#define IDC_EDIT14                      1117
#define IDC_EDIT_REMARKS                1117
#define IDC_EDIT15                      1118
#define IDC_EDIT_CUSTOM                 1118
#define IDC_COMBO_Week                  1120
#define IDC_COMBO_TimeSlot              1121
#define IDC_EDIT_minutee                1122
#define IDC_EDIT_seconde                1123
#define IDC_BUTTON_SET                  1124
#define IDC_BUTTON_GET                  1125
#define IDC_COMBO_LIST                  1126
#define IDC_EDIT_PATH                   1127
#define IDC_EDIT_PATH_IMPORT            1127
#define IDC_BUTTON_IMPORT               1128
#define IDC_BUTTON_EXPORT               1129
#define IDC_COMBO_USERTYPE              1130
#define IDC_EDIT_PATH_EXPORT            1130
#define IDC_RADIO_OPEN_TYPE1            1133
#define IDC_RADIO_OPEN_TYPE2            1134
#define IDC_BUTTON_STARTLISTEN          1135
#define IDC_BUTTON_STOPLISTEN           1136
#define IDC_DATETIMEPICKER_IN1          1137
#define IDC_DATETIMEPICKER_IN2          1138
#define IDC_LIST_SCREENSHOW             1138
#define IDC_DATETIMEPICKER_OUT1         1139
#define IDC_BUTTON_SCREENSHOW_ADD       1139
#define IDC_DATETIMEPICKER_OUT2         1140
#define IDC_BUTTON_SCREENSHOW_MODIFY    1140
#define IDC_BUTTON_SCREENSHOW_DELETE    1141
#define IDC_BUTTON_BROADCAST_ADD        1142
#define IDC_BUTTON_BROADCAST_MODIFY     1143
#define IDC_BUTTON_BROADCAST_DELETE     1144
#define IDC_LIST_BROADCAST              1145
#define IDC_BUTTON_ISSUE                1153
#define IDC_EDIT_SCREENSHOW_SCREENNO    1156
#define IDC_COMBO_SCREENSHOW_TEXTTYPE   1157
#define IDC_COMBO_SCREENSHOW_TEXTCOLOR  1158
#define IDC_COMBO1                      1158
#define IDC_COMBO_BROADCAST_TEXTTYPE    1158
#define IDC_COMBO_SCREENSHOW_TEXTROLLMODE 1159
#define IDC_COMBO_SCREENSHOW_ROLLSPEED  1160
#define ID_SET_SET1                     32771
#define ID_SET_SET2                     32772
#define ID_SET_SET3                     32773
#define ID_SET_PARKINGSPACELIGHTPLAN    32774
#define ID_SET_PARKINGSPACELIGHTSTATE   32775
#define ID_SET_PARKINGSPACELIGHTGROUP   32776
#define ID_STROBESET                    32778
#define ID_LATTICESCREEN                32779
#define ID_TALK                         32780
#define ID_BLACKWHILTLIST               32781
#define ID_LATTICESCREEN2               32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1159
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
