//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ImageTest.rc
//
#define IDD_IMAGETEST_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_EXPOSURE_DIALOG             130
#define IDD_BACKLIGHT_DIALOG            131
#define IDD_WHITEBALANCE_DIALOG         132
#define IDD_DEFOG_DIALOG                133
#define IDD_AUDIOSOURCE_DIALOG          138
#define IDD_FOCUSVALUE_DIALOG           139
#define IDC_REALPALY                    1000
#define IDC_IPADDRESS                   1002
#define IDC_EDIT_PORT                   1003
#define IDC_EDIT_USERMANE               1004
#define IDC_EDIT_PASSWD                 1005
#define IDC_BTN_LOGIN                   1006
#define IDC_BTN_LOGOUT                  1007
#define IDC_COMBO_CHANNELCOUNT          1008
#define IDC_SHARP_GET                   1012
#define IDC_SHARP_SET                   1013
#define IDC_CMB_ROTATE                  1016
#define IDC_CHECK_AUTOSYNCPHASE         1017
#define IDC_CHECK_FLIP                  1018
#define IDC_CHECK_ENHANCEMENT           1025
#define IDC_COMBO_WHITEBALANCETYPE      1036
#define IDC_SLIDER_RED                  1037
#define IDC_SLIDER_BLUE                 1038
#define IDC_SLIDER_GREEN                1039
#define IDC_EDIT_COLORTEMPERATURE       1040
#define IDC_EDIT_PHASE                  1040
#define IDC_BTN_DEFOG                   1041
#define IDC_BTN_EXPOSURE                1042
#define IDC_BTN_MINUS_RED               1047
#define IDC_BTN_MINUS_BLUE              1048
#define IDC_BTN_MINUS_GREEN             1049
#define IDC_BTN_PLUS_RED                1050
#define IDC_BTN_PLUS_BLUE               1051
#define IDC_BTN_PLUS_GREEN              1052
#define IDC_EDIT_CHANNELTITLE           1053
#define IDC_CHECK_DENOISE               1054
#define IDC_SLIDER7                     1055
#define IDC_BUTTON15                    1056
#define IDC_BUTTON16                    1057
#define IDC_COMBO8                      1058
#define IDC_CMB_MODE                    1058
#define IDC_COMBO9                      1059
#define IDC_CMB_TYPE                    1059
#define IDC_SLIDER8                     1060
#define IDC_SLIDER_BRIGHT               1060
#define IDC_BTN_MINUS_BRIGHT            1061
#define IDC_BTN_PLUS_BRIGHT             1062
#define IDC_SLIDER_CONTRASE             1063
#define IDC_BTN_MINUS_CONTRASE          1064
#define IDC_BTN_PLUS_CONTRASE           1065
#define IDC_SLIDER_SATURATION           1066
#define IDC_BTN_MINUS_SATURATION        1067
#define IDC_BTN_PLUS_SATURATION         1068
#define IDC_SLIDER_GAMMA                1069
#define IDC_BTN_MINUS_GAMMA             1070
#define IDC_BTN_PLUS_GAMMA              1071
#define IDC_CHECK_IRISAUTO              1072
#define IDC_SLIDER_WIDE                 1073
#define IDC_BTN_MINUS_WIDE              1074
#define IDC_BTN_PLUS_WIDE               1075
#define IDC_SLIDER_GLARE                1076
#define IDC_CMB_EXPOSURE                1076
#define IDC_BTN_MINUS_GLARE             1077
#define IDC_CMB_ANTIFLICKER             1077
#define IDC_BTN_PLUS_GLARE              1078
#define IDC_EDIT_COMPAENSATION          1078
#define IDC_EDIT_GAINMAX                1079
#define IDC_EDIT_GAINMIN                1080
#define IDC_EDIT_EXPOSUREIRIS           1081
#define IDC_CHECK_SLOWSHUTTER           1082
#define IDC_EDIT_SLOWEEXPOSURE          1083
#define IDC_EDIT_RECOVERYTIME           1084
#define IDC_EDIT_IRISMAX                1086
#define IDC_EDIT_SHARPNESS              1086
#define IDC_EDIT_IRISMIN                1087
#define IDC_EDIT_LEVEL                  1087
#define IDC_EDIT_SHUTTER                1088
#define IDC_EDIT_NOISELEVEL             1088
#define IDC_COMBO_BLACKMODE             1089
#define IDC_EDIT_EXPOSUREMAX            1089
#define IDC_COMBO_SHARPNESSMODE         1089
#define IDC_COMBO_BLACKLIGHTMODE        1090
#define IDC_EDIT_EXPOSUREMIN            1090
#define IDC_COMBO_VIDEONOISE            1090
#define IDC_EDIT_BOTTOM                 1091
#define IDC_EDIT_DELAY                  1092
#define IDC_COMBO_LIGHTMODE             1093
#define IDC_EDIT_CORRECTION             1094
#define IDC_EDIT_SENSITIVE              1095
#define IDC_COMBO_DEFOGMODE             1096
#define IDC_EDIT_INTENSITY              1097
#define IDC_COMBO_INTENSITYMODE         1098
#define IDC_EDIT_LIGHTLEVEL             1099
#define IDC_CHECK_DEFOG                 1100
#define IDC_CMB_FOCUSMODE               1101
#define IDC_CHECK_MIRROR                1103
#define IDC_BTN_GETCHANNELTITLE         1104
#define IDC_BTN_SETCHANNELTITLE         1105
#define IDC_BTN_GETAUDIO                1106
#define IDC_BTN_SETAUDIO                1107
#define IDC_EDIT_AUDIOIN                1108
#define IDC_EDIT_AUDIOOUT               1109
#define IDC_BTN_GETMODE                 1110
#define IDC_BTN_SETMODE                 1111
#define IDC_BTN_GETFOCUSMODE            1112
#define IDC_BTN_SETFOCUSMODE            1113
#define IDC_STATIC_BRIGHT               1114
#define IDC_STATIC_CONTRASE             1115
#define IDC_STATIC_SATURATION           1116
#define IDC_STATIC_GAMMA                1117
#define IDC_BTN_GETVIDEOCOLOR           1118
#define IDC_BTN_SETVIDEOCOLOR           1119
#define IDC_BTN_MINUS_ENHANCEMENT       1120
#define IDC_BTN_PLUS_ENHANCEMENT        1121
#define IDC_SLIDER_ENHANCEMENT          1122
#define IDC_STATIC_ENHANCEMENT          1123
#define IDC_BTN_GETENHANCEMENT          1124
#define IDC_BTN_SETENHANCEMENT          1125
#define IDC_COMBO_DAYNIGHT              1126
#define IDC_EDIT_SENSITIVITY            1127
#define IDC_BTN_GETDAYNIGHT             1128
#define IDC_BTN_SETDAYNIGHT             1129
#define IDC_BTN_GETLIGHTING             1130
#define IDC_BTN_SETLIGHTING             1131
#define IDC_BTN_GETSTABLE               1132
#define IDC_COMBO_STABLE                1133
#define IDC_BTN_SETSTABLE               1134
#define IDC_STATIC_WIDE                 1134
#define IDC_BTN_GETIRIS                 1135
#define IDC_STATIC_GLARE                1135
#define IDC_BTN_SETIRIS                 1136
#define IDC_EDIT_LEFT                   1136
#define IDC_EDIT_TOP                    1137
#define IDC_STATIC_BRIGHT2              1137
#define IDC_EDIT_RIGHT                  1138
#define IDC_STATIC_BRIGHT3              1138
#define IDC_SET                         1139
#define IDC_BTN_GETSHARPNESS            1139
#define IDC_GET                         1140
#define IDC_BTN_SETSHARPNESS            1140
#define IDC_BTN_BLACKLIGHT              1141
#define IDC_COMBO_TYPE                  1142
#define IDC_STATIC_BRIGHT4              1142
#define IDC_STATIC_RED                  1143
#define IDC_BTN_GETVIDEONOISE           1143
#define IDC_STATIC_BLUE                 1144
#define IDC_BTN_SETVIDEONOISE           1144
#define IDC_STATIC_GREEN                1145
#define IDC_STATIC_BRIGHT5              1145
#define IDC_BTN_WHITEBALANCE            1146
#define IDC_COMBO_AUDIOTYPE             1147
#define IDC_BTN_AUDIOTYPE               1148
#define IDC_DATETIMEPICKER_START        1178
#define IDC_DATETIMEPICKER_END          1179
#define IDC_RADIO_COAXIAL               1179
#define IDC_RADIO_BNC                   1180
#define IDC_RADIO_HDCVI_BNC             1181
#define IDC_RADIO_LINEIN                1182
#define IDC_RADIO_LINEIN1               1183
#define IDC_RADIO_LINEIN2               1184
#define IDC_RADIO_LINEIN3               1185
#define IDC_RADIO_MIC                   1186
#define IDC_RADIO_MIC1                  1187
#define IDC_RADIO_MIC2                  1188
#define IDC_RADIO_MIC3                  1189
#define IDC_RADIO_MICOUT                1190
#define IDC_RADIO_REMOTE                1191
#define IDC_RADIO_REMOTE1               1192
#define IDC_RADIO_REMOTE2               1193
#define IDC_RADIO_REMOTE3               1194
#define IDC_EDIT_SLOWSPEED              1195
#define IDC_CMB_SENSITIVITY             1197
#define IDC_CMB_IRCORRECTION            1198
#define IDC_CMB_LIMITMODE               1199
#define IDC_CHECK_AUTOFOCUS             1201
#define IDC_EDIT_LIMIT                  1202
#define IDC_BUTTON1                     1203
#define IDC_FOCUSVALUE                  1205
#define IDC_CHECK_2D                    1206
#define IDC_EDIT_2DLEVEL                1207
#define IDC_COMBO_ALGORITHMTYPE         1208
#define IDC_EDIT_TNFLEVEL               1209
#define IDC_EDIT_SNFLEVEL               1210
#define IDC_RADIO_ELECTRON              1211
#define IDC_RADIO_MECHANISM             1212
#define IDC_EDIT_GAIN                   1213
#define IDC_EDIT_ENDTIME_HOUR           1214
#define IDC_EDIT_ENDTIME_MINUTE         1215
#define IDC_EDIT_ENDTIME_SECOND         1216
#define IDC_EDIT_STARTTIME_HOUR         1217
#define IDC_EDIT_STARTTIME_MINUTE       1218
#define IDC_EDIT_STARTTIME_SECOND       1219

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1215
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
