//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ParkingSpaceDetector.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_REALLOADPICTURE_DIALOG      102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_BW_LIST              132
#define IDR_MENU1                       136
#define IDD_DIALOG_PARKINGSPACELIGHTGROUP 137
#define IDD_DIALOG_PARKING              137
#define IDD_DIALOG_PARKINGSPACELIGHTSTATE 139
#define IDC_IPADDRESS_IP                1001
#define IDC_EDIT_PORT                   1002
#define IDC_EDIT_USERNAME               1003
#define IDC_EDIT_FULL                   1134
#define IDC_EDIT_PASSWORD               1004
#define IDC_EDIT_FIRE                   1136
#define IDC_BUTTON_LOGIN                1005
#define IDC_EDIT_ALARM                  1137
#define IDC_BUTTON_LOGOUT               1006
#define IDC_BUTTON_EVENT_RULE           1007
#define IDC_BUTTON_DATA_QUERY           1008
#define IDC_COMBO_PREVIEW_CHANNEL       1009
#define IDC_STATIC_PN                   1011
#define IDC_STATIC_PREVIEW              1012
#define IDC_STATIC_PIC                  1013
#define IDC_STATIC_PICTURE              1013
#define IDC_CHECK_REFRESH_PIC           1019
#define IDC_BUTTON_START                1020
#define IDC_CHECK_SHOW_FULL_PIC         1021
#define IDC_LIST_EVENT_CHANNEL          1022
#define IDC_BUTTON_START_PREVIEW        1024
#define IDC_LISTCTRL_REAL_EVENT         1026
#define IDC_LIST_RESULT                 1027
#define IDC_STATIC_PL                   1028
#define IDC_COMBO_DISPLAY_FILTER        1039
#define IDC_BUTTON_MANUAL_SNAP          1043
#define IDC_BUTTON_STOP                 1044
#define IDC_BUTTON_CHN_ANTI_SEL         1045
#define IDC_BUTTON_STOP_PREVIEW         1046
#define IDC_BUTTON_TYPE_SEL_ALL         1047
#define IDC_LIST_EVENT_DISPLAY          1048
#define IDC_BUTTON_TYPE_ANTI_SEL        1048
#define IDC_EDIT_SPEED2                 1054
#define IDC_BUTTON_CLEAR                1055
#define IDC_STATIC_ALARM_COUNT          1056
#define IDC_BUTTON_CLEAR2               1057
#define IDC_BUTTON_CLEAR_DATA           1057
#define IDC_BUTTON_UPDATE_STATE         1065
#define IDC_STATIC_ACCURACY             1067
#define IDC_STATIC_LP                   1067
#define IDC_STATIC_EVENT_LP_IMAGE       1068
#define IDC_CHECK_WITH_DATA             1074
#define IDC_COMBO_CANNALMS              1075
#define IDC_BUTTON_PAUSE                1087
#define IDC_BUTTON_OPEN_STROBE          1089
#define IDC_COMBO_CHANNEL               1090
#define IDC_BUTTON_BW_LIST              1091
#define IDC_BUTTON_TRAFFIC_FLOW         1092
#define IDC_BUTTON_TRAFFIC_QUERY        1093
#define IDC_COMBO_VEHICLECOLOR2         1097
#define IDC_CHECK1                      1103
#define IDC_CHECK_FREE                  1103
#define IDC_CHECK2                      1104
#define IDC_CHECK_FULL                  1104
#define IDC_CHECK3                      1105
#define IDC_CHECK_FIRE                  1138
#define IDC_CHECK4                      1106
#define IDC_CHECK_ALARM                 1139
#define IDC_CHECK5                      1107
#define IDC_CHECK_CHARGING              1107
#define IDC_CHECK6                      1108
#define IDC_CHECK_OVERLINE              1108
#define IDC_CHECK_ORDER                 1109
#define IDC_BUTTON2                     1110
#define IDC_COMBO_SPACEFREE             1110
#define IDC_BUTTON_GET                  1110
#define IDC_COMBO_SPACEFULL             1111
#define IDC_COMBO_NETPORT1ABORT         1112
#define IDC_BUTTON_SET                  1113
#define IDC_COMBO_NETPORT2ABORT         1113
#define IDC_BUTTON_GETSTATE             1114
#define IDC_BUTTON_SETSTATE             1115
#define IDC_COMBO_CHARGING              1116
#define IDC_COMBO_FIREDETECTION         1124
#define IDC_COMBO_OVERLINE              1117
#define IDC_COMBO_ABNORMALALARM         1129
#define IDC_COMBO_ORDER                 1118
#define IDC_COMBO_SPACEFREE2            1130
#define IDC_COMBO_SPECIAL               1119
#define IDC_COMBO_SPACEFULL2            1133
#define IDC_CHECK_SPECIAL               1120
#define IDC_COMBO_FIREDETECTION2        1121
#define IDC_COMBO_SPACEFREE5            1122
#define IDC_COMBO_ABNORMALALARM2        1123
#define IDC_CHECK_SIGNAL                1125
#define IDC_CHECK_DOUBLE                1126
#define IDC_STATIC_1                    1127
#define IDC_STATIC_2                    1128
#define IDC_LIST_LIGHTGROUP_LIST        1131
#define IDC_EDIT2                       1132
#define IDC_BUTTON1                     1135
#define IDC_EDIT_FREE                   1140
#define ID_SET_SET1                     32771
#define ID_SET_SET2                     32772
#define ID_SET_SET3                     32773
#define ID_SET_PARKINGSPACELIGHTPLAN    32774
#define ID_SET_PARKINGSPACELIGHTSTATE   32775
#define ID_SET_PARKINGSPACELIGHTGROUP   32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1141
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
