//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TestOSD.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TESTOSD_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_CUSTOM_TEXT          129
#define IDD_DIALOG1                     130
#define IDC_BUTTON_START_PLAY           1000
#define IDC_STATIC_PIC                  1001
#define IDC_COMBO_TYPE_CHANNEL          1002
#define IDC_CHECK_COVE_CHANNEL          1003
#define IDC_CHECK_COVER_CHANNEL_MAIN    1003
#define IDC_COMBO_TYPE_TIME             1004
#define IDC_CHANNEL_FCOLOR              1005
#define IDC_BUTTON_SAVE_CHANNEL         1006
#define IDC_CHANNEL_BCOLOR              1007
#define IDC_CHECK_SHOWTIME              1008
#define IDC_TIME_FCOLOR                 1009
#define IDC_TIME_BCOLOR                 1010
#define IDC_BUTTON_SAVE_TIME            1011
#define IDC_CHECK_COVER_TIME            1012
#define IDC_EDIT_COVER_TEXT1            1013
#define IDC_CHECK_COVER_CHANNEL_EXTRA1  1013
#define IDC_CHECK_COVER_TEXT            1014
#define IDC_CHECK_COVER_TEXT1           1014
#define IDC_CHECK_COVER_CHANNEL_SNAP    1014
#define IDC_TEXT_FCOLOR                 1015
#define IDC_TEXT_FCOLOR1                1015
#define IDC_CHECK_COVER_CHANNEL_PREVIEW 1015
#define IDC_TEXT_BCOLOR                 1016
#define IDC_TEXT_BCOLOR1                1016
#define IDC_CHECK_COVER_CHANNEL_EXTRA2  1016
#define IDC_CHECK_COVER_TEXT2           1017
#define IDC_CHECK_COVER_CHANNEL_EXTRA3  1017
#define IDC_BUTTON_SAVE_TEXT            1018
#define IDC_CHECK_COVER_TIME_MAIN       1018
#define IDC_COMBO_TYPE_TIME1            1019
#define IDC_CHECK_COVER_TIME_EXTRA1     1019
#define IDC_TEXT_FCOLOR2                1020
#define IDC_CHECK_COVER_TIME_SNAP       1020
#define IDC_EDIT_FONT_SCALE             1021
#define IDC_TEXT_BCOLOR2                1022
#define IDC_CHECK_COVER_TIME_PREVIEW    1022
#define IDC_EDIT_IP                     1023
#define IDC_EDIT_COVER_TEXT2            1024
#define IDC_CHECK_COVER_TIME_EXTRA2     1024
#define IDC_EDIT_PORT                   1025
#define IDC_COMBO_TYPE_TIME2            1026
#define IDC_CHECK_COVER_TIME_EXTRA3     1026
#define IDC_EDIT_USER                   1027
#define IDC_CHECK_COVER_TEXT3           1028
#define IDC_BUTTON_GET_CHANNEL          1028
#define IDC_EDIT_PWD                    1029
#define IDC_TEXT_FCOLOR3                1030
#define IDC_BUTTON_GET_TIME             1030
#define IDC_TEXT_BCOLOR3                1031
#define IDC_EDIT_FONT_SIZE              1032
#define IDC_EDIT_COVER_TEXT3            1033
#define IDC_EDIT_FONT_SIZE_SUB1         1034
#define IDC_COMBO_TYPE_TIME4            1035
#define IDC_COMBO_TYPE_TIME3            1036
#define IDC_EDIT_FONT_SIZE_SUB2         1037
#define IDC_CHECK_COVER_TEXT4           1038
#define IDC_EDIT_FONT_SIZE_SUB3         1039
#define IDC_EDIT_TIME_TITLE_X1          1039
#define IDC_TEXT_FCOLOR4                1040
#define IDC_EDIT_FONT_SIZE_SNAP2        1041
#define IDC_EDIT_TIME_TITLE_X2          1041
#define IDC_TEXT_BCOLOR4                1042
#define IDC_EDIT_FONT_SIZE_SNAP         1043
#define IDC_EDIT_TIME_TITLE_X3          1043
#define IDC_EDIT_COVER_TEXT4            1044
#define IDC_COMBO_TYPE_TIME5            1045
#define IDC_EDIT_CHANNEL_TITLE_X        1046
#define IDC_EDIT_TIME_TITLE_X4          1046
#define IDC_CHECK_COVER_TEXT5           1047
#define IDC_EDIT_CHANNEL_TITLE_Y        1048
#define IDC_EDIT_TIME_TITLE_X5          1048
#define IDC_TEXT_FCOLOR5                1049
#define IDC_EDIT_TIME_TITLE_X           1050
#define IDC_EDIT_TIME_TITLE_X6          1050
#define IDC_TEXT_BCOLOR5                1051
#define IDC_EDIT_TIME_TITLE_Y           1052
#define IDC_EDIT_TIME_TITLE_Y1          1053
#define IDC_COMBO_CHANNEL               1053
#define IDC_EDIT_TIME_TITLE_Y2          1054
#define IDC_BUTTON_SAVE_COMMONINFO      1055
#define IDC_EDIT_TIME_TITLE_Y3          1055
#define IDC_EDIT_TIME_TITLE_Y4          1056
#define IDC_BUTTON_SAVE_COMMONINFO2     1056
#define IDC_BUTTON_GET_COMMONINFO       1056
#define IDC_EDIT_TIME_TITLE_Y5          1057
#define IDC_BUTTON_SET_CUSTOM_TEXT      1058
#define IDC_EDIT_TIME_TITLE_Y6          1058
#define IDC_COMBO_CHANNEL2              1059
#define IDC_COMBO_COVER                 1059
#define IDC_BUTTON_GET                  1061
#define IDC_EDIT_COVER_TEXT5            1062
#define IDC_COMBO_TYPE_TIME6            1063
#define IDC_BTN_PTZZOOM                 1065
#define IDC_CHECK_COVER_TEXT6           1066
#define IDC_GET                         1066
#define IDC_TEXT_FCOLOR6                1067
#define IDC_SET                         1067
#define IDC_TEXT_BCOLOR6                1068
#define IDC_CHECK_MAINBLEND             1068
#define IDC_EDIT_COVER_TEXT6            1069
#define IDC_CHECK_PREVIEWBLEND          1069
#define IDC_COMBO_TYPE_TIME7            1070
#define IDC_IPADDRESS_FRONT             1070
#define IDC_IPADDRESS_BACK              1071
#define IDC_EDIT_TIME                   1072
#define IDC_EDIT_LEFT                   1073
#define IDC_EDIT3                       1074
#define IDC_EDIT_TOP                    1074

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
