//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ThermalCamera.rc
//
#define IDD_ThermalCamera_DIALOG        102
#define IDR_MAINFRAME                   128
#define IDD_DLG_CONTROL                 134
#define IDR_MENU                        136
#define IDD_DLG_ALARM                   137
#define IDD_DLG_INFO                    138
#define IDD_DLG_QUERY                   139
#define IDD_DLG_PROPERTY                140
#define IDD_DLG_RULE                    141
#define IDD_DLG_GLOBAL                  142
#define IDD_DLG_STATISTCIS              143
#define IDD_DLG_ALARMCONFIG             144
#define IDD_DLG_LOCAL                   145
#define IDD_DLG_POINTINFO               147
#define IDD_DLG_ITEMINFO                148
#define IDD_DLG_HEATMAP                 155
#define IDD_DIG_THERMALSET              156
#define IDD_DIG_PTZ                     157
#define IDD_DIG_FIREWARNSET             158
#define IDD_DIG_CALIBRATE               159
#define IDD_GetTemper                   160
#define IDD_GETTEMPER                   160
#define IDD_DLG_GETTEMPER               160
#define IDC_REALPALY                    1000
#define IDC_HEATPALY                    1001
#define IDC_BTN_Login                   1003
#define IDC_BTN_LEAVE                   1004
#define IDC_IPADDRESS                   1005
#define IDC_CHECK_ORIGINAL              1006
#define IDC_CHECK_HEART                 1007
#define IDC_COMBO_PLAYMODE              1008
#define IDC_BUTTON_Play                 1009
#define IDC_BUTTON_STOP                 1010
#define IDC_EDIT_PORT                   1011
#define IDC_EDIT_USERNAME               1012
#define IDC_EDIT_PASSWORD               1013
#define IDC_COMBO_PTZDATA               1014
#define IDC_PTZ_LEFTUP                  1015
#define IDC_PTZ_UP                      1016
#define IDC_PTZ_RIGHTUP                 1017
#define IDC_PTZ_LEFT                    1018
#define IDC_PTZ_RIGHT                   1019
#define IDC_PTZ_LEFTDOWN                1020
#define IDC_PTZ_DOWN                    1021
#define IDC_PTZ_RIGHTDOWN               1022
#define IDC_ZOOM_WIDE                   1023
#define IDC_ZOOM_TELE                   1024
#define IDC_FOCUS_FAR                   1025
#define IDC_IRIS_OPEN                   1026
#define IDC_FOCUS_NEAR                  1027
#define IDC_IRIS_CLOSE                  1028
#define IDC_BTN_PTZMENU                 1029
#define IDC_BTN_PTZEXCTRL               1030
#define IDC_DATETIMEPICKER1             1070
#define IDC_STARTDAY                    1070
#define IDC_DATETIMEPICKER2             1073
#define IDC_ENDDAY                      1073
#define IDC_DATETIMEPICKER_S            1073
#define IDC_COMBO_QUERYTYPE             1074
#define IDC_DATETIMEPICKER_E            1074
#define IDC_COMBO_CHANNELNUM            1075
#define IDC_BTN_QUERY                   1076
#define IDC_EDIT2                       1080
#define IDC_EDIT3                       1081
#define IDC_COMBO_TIME                  1082
#define IDC_EDIT_Regions                1082
#define IDC_EDIT18                      1082
#define IDC_EDIT_POINT2_Y               1082
#define IDC_EDIT_GAINMODE               1083
#define IDC_EDIT_REFALECTED             1083
#define IDC_EDIT_TargetSize             1083
#define IDC_EDIT19                      1083
#define IDC_EDIT_POINT3_X               1083
#define IDC_EDIT4                       1084
#define IDC_EDIT5                       1085
#define IDC_EDIT_HLROI                  1085
#define IDC_EDIT_HYSTERESIS             1085
#define IDC_EDIT_COUNT                  1085
#define IDC_EDIT_EndTime                1085
#define IDC_EDIT_POINT4_X               1085
#define IDC_COMBO_ENABLE                1086
#define IDC_EDIT30                      1086
#define IDC_EDIT20                      1086
#define IDC_EDIT_POINT4_Y               1086
#define IDC_EDIT_CUSTOMNAME             1087
#define IDC_EDIT_RgnNum                 1087
#define IDC_COMBO_MODETYPE              1088
#define IDC_COMBO_UNIT                  1089
#define IDC_EDIT_ALARMCOUNT             1090
#define IDC_EDIT_COORDINATECOUNT        1091
#define IDC_EDIT_RELATIVE_HUMIDITY      1092
#define IDC_EDIT_DURATION               1092
#define IDC_COMBO1                      1093
#define IDC_COMBO2                      1094
#define IDC_COMBO3                      1095
#define IDC_EDIT6                       1096
#define IDC_COMBO_CONDITION             1096
#define IDC_EDIT_TIME                   1096
#define IDC_COMBO_Preset                1096
#define IDC_EDIT7                       1097
#define IDC_EDIT_PERIOD                 1097
#define IDC_EDIT_LENGTH                 1097
#define IDC_COMBO_Region                1097
#define IDC_EDIT8                       1098
#define IDC_EDIT_ALARMID                1098
#define IDC_EDIT_SENSORTYPE             1098
#define IDC_EDIT_ThermoSnapTimes        1098
#define IDC_COMBO_CH2                   1098
#define IDC_EDIT9                       1099
#define IDC_COMBO_CH1                   1099
#define IDC_COMBO_NOSIE                 1099
#define IDC_COMBO_NOISECHN              1099
#define IDC_EDIT10                      1100
#define IDC_EDIT_SATURATIONTEMP         1100
#define IDC_COMBO_FFCCHN                1100
#define IDC_COMBO_Group                 1100
#define IDC_EDIT11                      1101
#define IDC_EDIT_COLORTEMP_LEFT         1101
#define IDC_COMBO_LCECHN                1101
#define IDC_EDIT12                      1102
#define IDC_EDIT_COLORTEMP_RIGHT        1102
#define IDC_COMBO_NOISESCENE            1102
#define IDC_EDIT13                      1103
#define IDC_EDIT_COLORTEMP_TOP          1103
#define IDC_EDIT14                      1104
#define IDC_EDIT15                      1105
#define IDC_EDIT16                      1106
#define IDC_EDIT1                       1106
#define IDC_EDIT17                      1107
#define IDC_EDIT_HIGH_GREEN             1107
#define IDC_EDIT_RECORDLATCH            1107
#define IDC_COMBO_REGIONNUM             1108
#define IDC_EDIT_HIGH_BLUE              1108
#define IDC_EDIT_FUSIONRATE             1108
#define IDC_EDIT_PanGroupInterval       1108
#define IDC_EDIT_minutes                1108
#define IDC_EDIT_HIGH_ALPHA             1109
#define IDC_EDIT_HISTGRAMVALUE          1109
#define IDC_EDIT_index                  1109
#define IDC_EDIT_seconds                1109
#define IDC_EDIT_LOW_RED                1110
#define IDC_EDIT_LCEVALUE               1110
#define IDC_EDIT_NAME                   1110
#define IDC_EDIT_LOW_GREEN              1111
#define IDC_EDIT21                      1111
#define IDC_EDIT_noisevalue             1111
#define IDC_EDIT_NAME2                  1111
#define IDC_EDIT_LOW_BLUE               1112
#define IDC_EDIT_seconde                1112
#define IDC_POINTQUERY                  1113
#define IDC_EDIT_LOW_ALPHA              1113
#define IDC_EDIT_minutee                1113
#define IDC_EDIT_X                      1114
#define IDC_EDIT24                      1114
#define IDC_EDIT_speed                  1114
#define IDC_EDIT_houre                  1114
#define IDC_EDIT_Y                      1115
#define IDC_EDIT_PLongitude             1115
#define IDC_EDIT_Asschn1                1115
#define IDC_QUERYITEMINFO               1116
#define IDC_EDIT_PLongitude2            1116
#define IDC_EDIT_speed3                 1116
#define IDC_EDIT_Asschn2                1116
#define IDC_EDIT_PRESETID               1117
#define IDC_EDIT_PRESETNAME             1118
#define IDC_EDIT_1                      1118
#define IDC_EDIT_RULEID                 1119
#define IDC_EDIT_PLatitude              1119
#define IDC_EDIT_PAltitude              1120
#define IDC_COMBO_METERTYPE             1121
#define IDC_EDIT_X1                     1121
#define IDC_COMBO_TEMP                  1122
#define IDC_EDIT_Y1                     1122
#define IDC_EDIT_CYCLE                  1123
#define IDC_EDIT_X2                     1123
#define IDC_EDIT_ITEMNAME               1124
#define IDC_EDIT_Y2                     1124
#define IDC_COMBO_TEMPSTANUM            1125
#define IDC_EDIT_PLatitude2             1125
#define IDC_EDIT_ATMOSPHERICTEMP        1126
#define IDC_EDIT_PAltitude2             1126
#define IDC_EDIT_COEFFICIENT            1127
#define IDC_EDIT_X11                    1127
#define IDC_EDIT_DISTANCE               1128
#define IDC_EDIT_Y11                    1128
#define IDC_EDIT_RETEMP                 1129
#define IDC_EDIT_X22                    1129
#define IDC_COMBO_COLORBATCH            1130
#define IDC_EDIT_Y4                     1130
#define IDC_EDIT_Y22                    1130
#define IDC_COMBO_SHUTTER               1131
#define IDC_EDIT_COLORTEMP_BOTTOM       1131
#define IDC_COMBO_OSDMARK               1132
#define IDC_COMBO_COLORBAR              1132
#define IDC_COMBO_HOTSPOTFOLLOW         1133
#define IDC_COMBO_SWITCH                1134
#define IDC_EDIT_HIGH_RED               1135
#define IDC_COMBO_PSEUDOCOLOR           1136
#define IDC_COMBO_OPTREGION             1138
#define IDC_COMBO_ROITYPE               1139
#define IDC_COMBO_NUM                   1140
#define IDC_COMBO_GAINMODE              1141
#define IDC_EDIT_HIGHVALUE              1142
#define IDC_EDIT_LHROI                  1143
#define IDC_EDIT_LOWVALUE               1144
#define IDC_EDIT_RULEAMOUNT             1146
#define IDC_COMBO_POINTNUM              1147
#define IDC_COMBO_ALARMENABLE           1148
#define IDC_COMBO_RESULTTYPE            1149
#define IDC_EDIT_THRESHOLD              1151
#define IDC_COMBO_RULEID                1153
#define IDC_COMBO_LOCALCONFIG           1154
#define IDC_STARTLISTEN                 1155
#define IDC_STOPLISTEN                  1156
#define IDC_STARTTIME                   1157
#define IDC_STARTLISTEN2                1157
#define IDC_ENDTIME                     1158
#define IDC_STOPLISTEN2                 1158
#define IDC_EDIT_QUERYBEGINNUM          1159
#define IDC_BTN_GET                     1160
#define IDC_BTN_SET                     1161
#define IDC_COMBO_ALARMID               1168
#define IDC_EDIT_ALARMAMOUNT            1169
#define IDC_STARTFETCH                  1170
#define IDC_ATTACH                      1172
#define IDC_STOP                        1173
#define IDC_EDIT_STATUS                 1174
#define IDC_EDIT_HEIGHT                 1175
#define IDC_EDIT_WIDTH                  1176
#define IDC_BUTTON1                     1178
#define IDC_BTNIMGANDTEMSAVE            1178
#define IDC_BUTTON_GETFFC               1178
#define IDC_BUTTON_SetPanGroupScan      1178
#define IDC_GETTEMPER                   1178
#define IDC_BUTTON_SETFFC               1179
#define IDC_BUTTON_GetPanGroupScan      1179
#define IDC_BUTTON3                     1180
#define IDC_BUTTON_DOFFC                1180
#define IDC_BUTTON_GETFUSION            1181
#define IDC_BUTTON_GetPanGroup          1181
#define IDC_BUTTON_SETFUSION            1182
#define IDC_BUTTON_SetPanGroupLimit     1182
#define IDC_BUTTON_GETLCESTATE          1183
#define IDC_BUTTON_pause                1183
#define IDC_BUTTON_SETLCESTATE          1184
#define IDC_BUTTON_gotoPanPos           1184
#define IDC_BUTTON8                     1185
#define IDC_BUTTON_GETNOISE             1185
#define IDC_BUTTON9                     1186
#define IDC_BUTTON_SETNOISE             1186
#define IDC_CHECK1                      1187
#define IDC_CHECK_noise                 1187
#define IDC_BUTTON10                    1188
#define IDC_CHECK_PanGroupEnable        1188
#define IDC_CHECK_RCH2                  1188
#define IDC_BUTTON_FOCUS                1188
#define IDC_COMBO_FFCMODE               1189
#define IDC_CHECK_SCH1                  1189
#define IDC_EDIT_FFCPERIOD              1190
#define IDC_RADIO_antijamming           1190
#define IDC_COMBO_FUSIONMODE            1191
#define IDC_RADIO_highresponse          1191
#define IDC_RADIO_PtzPreset             1192
#define IDC_RADIO_SpaceExClude          1193
#define IDC_COMBO_Week                  1194
#define IDC_BUTTON_GETFIRESET           1195
#define IDC_CHECK_RECORD                1196
#define IDC_CHECK_ALARMOUT              1197
#define IDC_CHECK_MAIL                  1198
#define IDC_CHECK_PTZ                   1199
#define IDC_CHECK_SNAP                  1200
#define IDC_RADIO5                      1201
#define IDC_RADIO_Auto                  1201
#define IDC_RADIO6                      1202
#define IDC_RADIO_Manual                1202
#define IDC_CHECK_VisualOverview        1203
#define IDC_CHECK_VisualDetail          1204
#define IDC_BUTTON_SETFIRESET           1205
#define IDC_BUTTON_GETFIREEXT           1206
#define IDC_BUTTON_SETFIREEXT           1207
#define IDC_EDIT_Longitude              1208
#define IDC_CHECK_SCH2                  1208
#define IDC_EDIT_Latitude               1209
#define IDC_BUTTON_GETFIREMODESET       1209
#define IDC_EDIT_Altitude               1210
#define IDC_BUTTON_SETFIREMODESET       1210
#define IDC_CHECK_Config                1211
#define IDC_CHECK_Time                  1211
#define IDC_BUTTON_GETDEVLOCATION       1212
#define IDC_BUTTON_SETDEVLOCATION       1213
#define IDC_COMBO_PointID               1214
#define IDC_COMBO_CALID                 1215
#define IDC_BUTTON_GETCAL               1216
#define IDC_BUTTON_SETCAL               1217
#define IDC_BUTTON_DELCAL               1218
#define IDC_BUTTON_GETALLCAL            1219
#define IDC_CHECK_LimitEnable           1220
#define IDC_BUTTON_GETLOCATIONCAL       1220
#define IDC_COMBO_LimitMode             1221
#define IDC_BUTTON_SETLOCATIONCAL       1221
#define IDC_EDIT_PanGroupName           1222
#define IDC_COMBO_PointID2              1222
#define IDC_EDIT_PanGroupSpeed          1223
#define IDC_COMBO_CALID2                1223
#define IDC_BUTTON_SetPanGroup          1224
#define IDC_COMBO_CH3                   1225
#define IDC_COMBO_SetLimitMode          1226
#define IDC_BUTTON_resume               1227
#define IDC_CHECK_Enable                1228
#define IDC_COMBO_Index                 1228
#define IDC_COMBO_CH4                   1229
#define IDC_EDIT_Sensitivity            1230
#define IDC_COMBO_Index2                1230
#define IDC_COMBO_TimeSlot              1231
#define IDC_EDIT_StartTime              1232
#define IDC_LIST_ALARM                  1233
#define IDC_CHECK_RCH1                  1233
#define IDC_EDIT_ALARMOUTLATCH          1234
#define IDC_EDIT_FireDuration           1235
#define IDC_LIST_Regions                1236
#define IDC_LIST_FIREWARNING            1237
#define IDC_COMBO_CHN                   1238
#define IDC_STATIC_PICTURE              1239
#define IDC_STATIC_MESSAGE              1240
#define IDC_EDIT_hours                  1247
#define IDC_EDIT_preset                 1248
#define IDC_EDIT_POINT1_X               1249
#define IDC_EDIT_POINT1_Y               1250
#define IDC_EDIT_POINT2_X               1251
#define IDC_EDIT_POINT3_Y               1252
#define IDC_COM_CHANNEL                 1253
#define IDC_EDIT_BRIGHTNESS             1334
#define IDC_EDIT_SHARPNESS              1335
#define IDC_EDIT_ZOOM                   1336
#define IDC_EDIT_GAMMA                  1337
#define IDC_EDIT_COLOR                  1338
#define IDC_EDIT_OPTINDICATOR           1339
#define IDC_EDIT_GAINCTL                1340
#define IDC_EDIT_MAXGAIN                1341
#define IDC_EDIT_GAINBALANCE            1342
#define IDC_EDIT_OPTREGION              1343
#define IDC_EDIT_ROITYPE                1344
#define IDC_EDIT_AMOUNT                 1345
#define IDC_EDIT_TOP                    1346
#define IDC_EDIT_RIGHT                  1347
#define IDC_EDIT_LEFT                   1348
#define IDC_EDIT_BOTTOM                 1349
#define IDC_EDIT_REGIONNUM              1350
#define IDC_EDIT_SERIALNUM              1351
#define IDC_SOFTVER                     1352
#define IDC_EDIT_FIRMVER                1353
#define IDC_EDIT_LIBVER                 1354
#define IDC_EDIT_MEASURETYPE            1355
#define IDC_EDIT_TEMP                   1356
#define IDC_EDIT_MAXTEMP                1357
#define IDC_EDIT_UNIT                   1358
#define IDC_EDIT_MINTEMP                1359
#define IDC_EDIT_MIDTEMP                1360
#define IDC_EDIT_STDTEMP                1361
#define IDC_EDIT_PRESETNUM              1362
#define IDC_EDIT_RULENUM                1363
#define IDC_EDIT_MEASURENAME            1364
#define IDC_EDIT_CHANNEL                1365
#define ID_CONTROL                      32774
#define ID_ALARM                        32775
#define ID_INFO                         32776
#define ID_QUERY                        32777
#define ID_Preperty                     32778
#define ID_RULE                         32779
#define ID_GLOBAL                       32780
#define ID_STATISTCIS                   32781
#define ID_ALARMSET                     32782
#define ID_LOCAL                        32783
#define ID_                             32784
#define ID_HEATMAP                      32784
#define ID_PRESETINFO                   32785
#define ID_POINTINFO                    32786
#define ID_ITEMINFO                     32787
#define ID_THERMALSET                   32789
#define ID_FIREWARN_FIREWARNSET         32790
#define ID_FIREWARN_CALIB               32791
#define ID_FIREWARN_CALIBRATE           32792
#define ID_PTZ                          32793
#define ID_TEMPERINFO                   32794

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1254
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
